### ISSUE TITLE
Deploy UI5 project stuck

### ISSUE THREAD

**Issue by RaynDol** [cloudfoundry-incubator/multiapps-controller#105]
HI,

I've **very simple** UI5 application which I build with the MTA Build tool as suggested in the readme,
I try to deploy it to SAP Cloud Foundry
The problem is after two min the deployment process stuck with starting the application and nothing happen.

Any idea what it could be ?  

Btw, in this case could you improve the logs to reflect the status, in fact the application is not starting

New MTA version: 0.0.1
  Deployed MTA version: 0.0.1
  Building cloud deployment model...
  Building cloud undeployment model...
  Validating services to create...
  Validating applications to deploy...
  Adding domains...
  Deleting unused reserved routes...
  Creating or updating services...
  Preparing applications deployment...
  Checking application "ui5"...
  Application "ui5" exists
  Updating application "ui5"...
  Application "ui5" is not modified and will not be updated
  Uploading application "ui5"...
  Matched files count: 17
  Matched resources processed, total size is 7,155,484
  Upload status: queued
  Upload status: failed
  Checking upload status of application "ui5"...
  Scaling application "ui5"...
  Actions that should be executed on application ui5: [STOP, STAGE, START]
  Stopping application "ui5"...
  **Starting application "ui5"...** 

Best Regards,
Rayn

**Comment by KristianShishoev** [comment]
Can't tell you much without seeing the logs.
So can you send us deploy-service logs to make more detailed analyze of the problem ?

Regards,
Kristian

**Comment by mptsonev** [comment]
Hi Rayn,

Any updates from your side?

Regards,
Mihail
