### ISSUE TITLE
Docker images support

### ISSUE THREAD

**Issue by lextiz** [cloudfoundry-incubator/multiapps-controller#205]
Hi guys,

Do you support or plan to support [docker image](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html) module type? It would fit nicely to MTA ability to refer a ready artifact from artifact registry.

Thanks!

**Comment by nvvalchev** [comment]
Hi! Yes, we have the [docker](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html) support on our plans, however there is currently more important stuff the team is focused on like optimizing the MTA deployment performance and some other planned refactorings. Any contributions are welcome, though!

**Comment by boyan-velinov** [comment]
Hi,
It is already implemented in #335 
You can also find more details in documentation: https://help.sap.com/viewer/TEST/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/37eedfdf814d4845ad784334d7ad6f8e.html?q=MTA%20Module%20Types,%20Resource%20Types,%20and%20Parameters%20for%20Applications%20in%20the%20Cloud%20Foundry%20Environment
