### ISSUE TITLE
Report error from recent app logs in case of app crash during cf deploy

### ISSUE THREAD

**Issue by VaskoBozhurski** [cloudfoundry-incubator/multiapps-controller#294]
### Description
Currently at deployment MultiApps Controller output is limited to app stage/start output, which is fine. However, in case of app crashes it is not that convenient as the user has to retrieve the recent app logs in order to see the reason for the crash.

E.g. currently there is only the following output:
```
Application "example-app" staged
Starting application "example-app"...
0 of 1 instances running (1 running)
0 of 1 instances running (1 crashed)
Error starting application "example-app": Some instances have crashed
```

### Expected Behavior 
In case of app crash in staging/start the output from above should be enhanced to contain the errors or last error from the recent app logs, such as:
```
2018-10-17T16:25:40.99+0300 [APP/PROC/WEB/0] ERR Cannot calculate JVM memory configuration: There is insufficient memory remaining for heap. Memory available for allocation 256M is less than allocated memory 644084K (-XX:ReservedCodeCacheSize=240M, -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=132084K, -Xss1M * 250 threads)
```

### Internal Tracking Number:
LMCROSSITXSADEPLOY-547

**Comment by boyan-velinov** [comment]
Done with https://github.com/cloudfoundry-incubator/multiapps-controller/pull/434
