### ISSUE TITLE
Blue green deployment caused a downtime in our internal productive system 

### ISSUE THREAD

**Issue by I816674** [cloudfoundry-incubator/multiapps-controller#431]
### Description
Blue green deployment caused a downtime in our internal productive system 
in our pipeline we call the piper function deployToCloudFoundry  (using the option blue green deployment) which is using the plugin blue-green-deploy   1.4.0
the scenario where the downtime occurred is the following:

the first pipeline job did the following steps:
https://gist.github.com/I816674/b2cde969edc8753b708e3f4f25b0dad3
and its MAIN LOG
https://gist.github.com/I816674/cac1afb3d1c0dd4b6eaefa06c0bddda0

in this job a green deployment succeeded and started the apps with the expected routes correctly but failed to delete/undeploy the blue apps  so both green and blue were running at the same time and then the jenkins job failed

then we executed again the pipeline, there the blue-green-deploy started by aborting the last operation and then detected that blue and green were deployed and decided for the green to be the candidate to be redeployed and this caused a downtime of our services in an internal productive system! which will would like to avoid for the next times...
here is the steps executed in the second pipeline:
https://gist.github.com/I816674/16b0a72f692908743bbe52ac49d91a5f
and its MAIN LOG
https://gist.github.com/I816674/7bb78c6f0041f09741c23bd11a142f54

**Comment by MatthiasSchmalz** [comment]
The 2nd deployment showed this logging:
_There are both blue and green applications already deployed for MTA "fdc-cf-service"
Assuming BLUE is the live and GREEN is the idle MTA color_

Dangerous is to do an assumption here, which could be wrong and cause a downtime. In fact green has been active already.

**Comment by MatthiasSchmalz** [comment]
Any updates?

**Comment by I816674** [comment]
They created a BI to resolve this issue which we can track:
https://sapjira.wdf.sap.corp/browse/LMCROSSITXSADEPLOY-1410

**Comment by boyan-velinov** [comment]
Hello,

The fix is done with:
https://github.com/cloudfoundry-incubator/multiapps-controller/pull/478

Please verify that everything is working as expected.

Best Regards,
Boyan

**Comment by nictas** [comment]
No updates for a while, so I'll assume that the fix is working and close this issue.
