### ISSUE TITLE
deployment does not start

### ISSUE THREAD

**Issue by lucatoldo** [cloudfoundry-incubator/multiapps-controller#581]
Description
I'be built an mtar using mbt and have tried to deploy it with cf deploy.
While it is a java application, is not a springboot and it has many dependencies. Therefore I've built a zip . For the deployment, that zip has to be unzipped and then a specific commandline has to be executed. I do not know where to specify this behavor.

Your environment
MBT version 0.2.10
MultiApps CF CLI Plugin version - 2.1.1
which CF vendor is used - cf version 6.39.1+efdd631d2.2018-09-18

This is the log I get..

Staging app and tracing logs...
   Downloading sap_java_buildpack...
   Downloaded sap_java_buildpack
   Cell a4345ac6-b96b-4a01-973a-4638e4192c8e creating container for instance 210a58c0-31da-44d7-bdd3-c175eb183b57
   Cell a4345ac6-b96b-4a01-973a-4638e4192c8e successfully created container for instance 210a58c0-31da-44d7-bdd3-c175eb183b57
   Downloading app package...
   Downloaded app package (522.8M)
   Compiling Java application...
   Java XS Buildpack Version: 1.14.0
   SEVERE: Unhandled exception in Buildpack main method: None of the available runtimes: [Tomee, Tomee7, Tomcat, Java Main] support the application in the specified path. Failed to compile droplet: Failed to compile droplet: exit status 9
   Exit status 223
   Cell a4345ac6-b96b-4a01-973a-4638e4192c8e stopping instance 210a58c0-31da-44d7-bdd3-c175eb183b57
   Cell a4345ac6-b96b-4a01-973a-4638e4192c8e destroying container for instance 210a58c0-31da-44d7-bdd3-c175eb183b57
   Cell a4345ac6-b96b-4a01-973a-4638e4192c8e successfully destroyed container for instance 210a58c0-31da-44d7-bdd3-c175eb183b57
Error staging application: App staging failed in the buildpack compile phase

**Comment by lucatoldo** [comment]
Figured out that the problem was due to the fact that the _mtad.yaml_ generated by **mbt** over-wrote the type of the application and replaced "_java_" with "_java.tomcat_", leading to not starting.

**Comment by valentinEmpy** [comment]
Hello @lucatoldo,

Do I understand correctly you have managed to fix your issue?
I will close it now, in case you need further assistance please re-open it.
