### ISSUE TITLE
[FEATURE REQUEST] Update service config on redeploy

### ISSUE THREAD

**Issue by sgarland** [cloudfoundry-incubator/multiapps-controller#663]
### Description
Currently MTA deployment does not update service configuration (meaning no equivalent of `cf update-service SERVICE_INSTANCE -c CONFIG` runs during a redeployment).

On redeployment the current code checks for changes in service plan, service keys, service credentials and tags, but not configuration.

An example of where this would be useful is in an MTA that creates a UAA service instance.
When scopes/role templates/authorities are added to the configuration of the UAA instance in the `mta.yaml` it would be useful if a redeployment would result in the configuration of the previously created UAA service instance being updated (without the service instance being recreated).

**Comment by nictas** [comment]
Hi @sgarland,

Thanks for reporting this issue, but this feature is already implemented. If it didn't work for you, then it must have regressed or you've hit a corner case we haven't thought of. Can you give us 2 `mtad.yaml`s with which we can reproduce the issue?

**Comment by sgarland** [comment]
Thank you. You are right. It is implemented.
I updated to the latest CLI plugin version and created a simplified example.
I was able to verify that the service configuration was updated on redeployment.
