### ISSUE TITLE
Supported module types

### ISSUE THREAD

**Issue by kepair** [cloudfoundry-incubator/multiapps-controller#865]
### Description

I work at SAP providing support for SCP.
In many examples I see that they use `approuter.nodejs` module type ([here](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/e8059587e95a407f91d2dcf5b11568d5.html) for example). 

I know this is vendor neutal, but checking the [manifest.yml](https://github.com/cloudfoundry-incubator/multiapps-controller/blob/master/com.sap.cloud.lm.sl.cf.web/manifests/manifest.yml#L26) for the supported module types I see that `nodejs` is there, but nothing about approuter.

I though maybe it doesn't matter what you put in front, but it does, it won't accept `invented.nodejs`.

Is there a place where I can see what SCP CF accepts as module type?
Do you know where in SAP can I get this info?

### Your environment
*	Cloud MTA Build Tool version 1.0.12
*	MultiApps CF CLI Plugin version - 2.3.1
*	which CF vendor is used - SAP CF

Thanks,
Pedro

**Comment by theghost5800** [comment]
Hi @kepair ,

You have reached MTA Deploy Service team. as you find out in our manifest.yml we have defined module-types for OSS project but in SAP SCP we have additional module-types which you can see at this [page](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/177d34d45e3d4fd99f4eeeffc5814cf1.html) in MTA Module Types section. About `approuter.nodejs` module-type we don't have such type in Deploy Service, maybe this is module-type which is resolved by Cloud MTA Build Tool to another module-type. You can try to open github issue to [MBT project](https://github.com/SAP/cloud-mta-build-tool)

Best Regards,
Kristian
