### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by balajimurugesan2016** [cloudfoundry-incubator/multiapps-controller#960]
Hi,

I'm Balaji from Germany
I went through the project and would love to contribute to new features and issues towards the project. How could I start?  Could someone please help me with a walkthrough?

Ciao,
Balaji Vengatesh Murugesan

**Comment by balajimurugesan2016** [comment]
__

**Comment by balajimurugesan2016** [comment]
acc

**Comment by ddonchev** [comment]
Hi @balajimurugesan2016,

You can check out [this doc](https://github.com/cloudfoundry-incubator/multiapps-controller/blob/master/CONTRIBUTING.md#do-you-want-to-contribute-to-the-code-base) for the first steps in setting up the project in a dev environment. Have in mid that the code base was very recently ported to java 11 and chances are that this was not reflected there. 
- In general, you need maven, an IDE ( both InteliJ and Eclipse will do ), and a CF environment with a postgresql service to run the backend. 
- All repos have a decent unit test coverage. After merge or on PR we can run an integration test suite on our own infrastructure ( the integration tests setup & code are too coupled with the infrastructure to OSS and to exect anyone to set up on their own ). Load & Stress tests are again internally executed before release on the main dev branch (usually bi-weekly).
- The legal aspects for contribution are covered by the CF foundation's contributor licence agreement. Upon PR, a CLA bot will pitch in and guide through the process.

If you have questions, you can find me and a few developers from the team in [this slack channel](https://cloudfoundry.slack.com/archives/C9V0Z8ZPF).

Do you have any particular features in mind? Could you share details about the stories? We may have similar, envisioned in the team backlog.

**Comment by balajimurugesan2016** [comment]
Hi Dido ,

As of now, I don't have any feature requests. But I'm an avid developer/user for cloud foundry services. We have a lot of requests coming up in the future. So naturally, I'm more interested to know the inner workings and contribute towards the project.

Best Regards,
Balaji Vengatesh Murugesan
